
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import PhasedVotingContractArtifactJson from './PhasedVoting.json' assert { type: 'json' };
export const PhasedVotingContractArtifact = PhasedVotingContractArtifactJson as ContractArtifact;

/**
 * Type-safe interface for contract PhasedVoting;
 */
export class PhasedVotingContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, PhasedVotingContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, PhasedVotingContract.artifact, wallet) as Promise<PhasedVotingContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PhasedVotingContract>(Point.ZERO, wallet, PhasedVotingContractArtifact, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<PhasedVotingContract>(publicKey, wallet, PhasedVotingContractArtifact, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PhasedVotingContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** _assert_authorized(caller: struct) */
    _assert_authorized: ((caller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _assert_closed() */
    _assert_closed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _assert_open() */
    _assert_open: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _close_voting_room() */
    _close_voting_room: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _initialize(admin: struct) */
    _initialize: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _update_vote_result(index: field) */
    _update_vote_result: ((index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_vote() */
    burn_vote: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** close_voting_room() */
    close_voting_room: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(contract_address: field, nonce: field, storage_slot: field, preimage: array) */
    compute_note_hash_and_nullifier: ((contract_address: FieldLike, nonce: FieldLike, storage_slot: FieldLike, preimage: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_result(index: field) */
    get_result: ((index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lock_vote(vote: field) */
    lock_vote: ((vote: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
